### ISSUE TITLE
WLAN completely unsupported

### ISSUE THREAD

**Issue by npyl** [Conky-for-macOS/conky-for-macOS#17]
The build option `BUILD_WLAN` is only available for Linux.

~We either need to provide an option `BUILD_DARWIN_WLAN` or~ patch the original code and keep `BUILD_WLAN`

**Comment by npyl** [comment]
I chose to patch the original code to make BUILD_WLAN available for all OS.  It is also set to OFF by default for backwards-compatibility.  This should be the optimal behaviour.

See commits: 800992d1559950701e75c40e477565643df1fddb, 504d27c8764cb05b9f5533ad89013876c7202972, 51f5350392b153b1edcbf600f740c02415c9aea4.

**Comment by npyl** [comment]
For macOS there are some options: (Apple doesn't really want you to know WIFI stuff 👻)
- Use `CoreWLAN.framework`
- Use `airport` command line utility
- Use the private framework `Apple80211.framework`

First option means calling Obj-C somehow in our C++ project. (Probably convert `darwin.cc` to `darwin.mm` 😂)...

Second option means using pipes / parsing and ugly and tedious code just to get an `essid` and other information.

Third option means reverse-engineering, ([this](http://newosxbook.com/articles/11208ellpA.html) can help), probably ***later dealing with obsolete APIs***, but too much fun.

Seems to me like the 3rd option is the best.

**Comment by npyl** [comment]
We are going for the `PrivateFramework` approach.

**Comment by npyl** [comment]
082076a has been deleted.  I decided not to go with this approach. Instead I am going to rename `darwin.cc` to `darwin.mm` and thus enable `CoreWLAN.framework`

**Comment by npyl** [comment]
This can now be closed as I have pretty-much done what I could to implement WLAN stats.  They may be completely wrong but the solution may be one step away...

I am not well-versed with WLAN terminology / theory thus I cannot provide better implementation.

The work can be seen in the [wifi](https://github.com/Conky-for-macOS/conky-for-macOS/tree/wifi) branch.

More patches may come in the way but this can be considered done :)

**Comment by npyl** [comment]
@matmunn Hi Mat, could you please take a look in my [code](https://github.com/brndnmtthws/conky/compare/master...Conky-for-macOS:wifi) for WLAN?  I really don't know anything about WLAN terminology (haven't yet gone to uni) and don't really understand anything around the internet.

If you don't know either thats ok 😄

**Comment by matmunn** [comment]
Looks ok to me, from what I understand

**Comment by npyl** [comment]
@matmunn Thanks Mat!
