### ISSUE TITLE
Conky loads but seems to have stuck

### ISSUE THREAD

**Issue by npyl** [Conky-for-macOS/conky-for-macOS#18]
# Steps

Compile conky following Unix-Makefiles process
Use default settings
Run `make install` at the end

# Result: 

Conky starts, loads to the point that says `conky: drawing to created window (0x600001)` and stays there stuck.  In activity monitor we notice excessive CPU usage.

**Comment by matmunn** [comment]
I also seem to have high CPU usage on macOS 10.13.5, having done `make install`.

It also happens regardless of using `double_buffer` or not.

**Comment by npyl** [comment]
The problem seems to reside in `darwin.cc` in `get_top_info_for_kinfo_proc` and specifically in the while-loop. 
I have amended the problem by adding a `usleep()` call with a minimum value of `500` usec.  

Please check the latest commit.

**Comment by matmunn** [comment]
Significant improvement for me, gone from 99.6% CPU usage to 2.9.

**Comment by npyl** [comment]
I think this can be closed now!
