### ISSUE TITLE
Compiler errors on cmake

### ISSUE THREAD

**Issue by DenisBopp** [Conky-for-macOS/conky-for-macOS#27]
Get this error when doing  cmake.

error log:>
Determining if files sys/statfs.h exist failed with the following output:
Change Dir: /Users/denisbopp/conky-for-macOS/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_1f6aa/fast"
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_1f6aa.dir/build.make CMakeFiles/cmTC_1f6aa.dir/build
Building C object CMakeFiles/cmTC_1f6aa.dir/HAVE_SYS_STATFS_H.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -std=c99     -o CMakeFiles/cmTC_1f6aa.dir/HAVE_SYS_STATFS_H.c.o   -c /Users/denisbopp/conky-for-macOS/build/CMakeFiles/CheckIncludeFiles/HAVE_SYS_STATFS_H.c
/Users/denisbopp/conky-for-macOS/build/CMakeFiles/CheckIncludeFiles/HAVE_SYS_STATFS_H.c:2:10: fatal error: 'sys/statfs.h' file not found
#include <sys/statfs.h>
         ^~~~~~~~~~~~~~
1 error generated.
make[1]: *** [CMakeFiles/cmTC_1f6aa.dir/HAVE_SYS_STATFS_H.c.o] Error 1
make: *** [cmTC_1f6aa/fast] Error 2

Source:
/* */
#include <sys/statfs.h>

int main(void){return 0;}

Determining if files sys/inotify.h exist failed with the following output:
Change Dir: /Users/denisbopp/conky-for-macOS/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_d56d3/fast"
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_d56d3.dir/build.make CMakeFiles/cmTC_d56d3.dir/build
Building C object CMakeFiles/cmTC_d56d3.dir/HAVE_SYS_INOTIFY_H.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -std=c99     -o CMakeFiles/cmTC_d56d3.dir/HAVE_SYS_INOTIFY_H.c.o   -c /Users/denisbopp/conky-for-macOS/build/CMakeFiles/CheckIncludeFiles/HAVE_SYS_INOTIFY_H.c
/Users/denisbopp/conky-for-macOS/build/CMakeFiles/CheckIncludeFiles/HAVE_SYS_INOTIFY_H.c:2:10: fatal error: 'sys/inotify.h' file not found
#include <sys/inotify.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [CMakeFiles/cmTC_d56d3.dir/HAVE_SYS_INOTIFY_H.c.o] Error 1
make: *** [cmTC_d56d3/fast] Error 2

Source:
/* */
#include <sys/inotify.h>

int main(void){return 0;}

Determining if the pipe2 exist failed with the following output:
Change Dir: /Users/denisbopp/conky-for-macOS/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_7be2e/fast"
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_7be2e.dir/build.make CMakeFiles/cmTC_7be2e.dir/build
Building C object CMakeFiles/cmTC_7be2e.dir/CheckSymbolExists.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -std=c99     -o CMakeFiles/cmTC_7be2e.dir/CheckSymbolExists.c.o   -c /Users/denisbopp/conky-for-macOS/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
/Users/denisbopp/conky-for-macOS/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:19: error: use of undeclared identifier 'pipe2'; did you mean 'pipe'?
  return ((int*)(&pipe2))[argc];
                  ^~~~~
                  pipe
/usr/include/unistd.h:469:6: note: 'pipe' declared here
int      pipe(int [2]);
         ^
1 error generated.
make[1]: *** [CMakeFiles/cmTC_7be2e.dir/CheckSymbolExists.c.o] Error 1
make: *** [cmTC_7be2e/fast] Error 2

File /Users/denisbopp/conky-for-macOS/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <unistd.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pipe2
  return ((int*)(&pipe2))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if files sys/soundcard.h exist failed with the following output:
Change Dir: /Users/denisbopp/conky-for-macOS/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_1eb25/fast"
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_1eb25.dir/build.make CMakeFiles/cmTC_1eb25.dir/build
Building C object CMakeFiles/cmTC_1eb25.dir/HAVE_SOME_SOUNDCARD_H.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -std=c99     -o CMakeFiles/cmTC_1eb25.dir/HAVE_SOME_SOUNDCARD_H.c.o   -c /Users/denisbopp/conky-for-macOS/build/CMakeFiles/CheckIncludeFiles/HAVE_SOME_SOUNDCARD_H.c
/Users/denisbopp/conky-for-macOS/build/CMakeFiles/CheckIncludeFiles/HAVE_SOME_SOUNDCARD_H.c:2:10: fatal error: 'sys/soundcard.h' file not found
#include <sys/soundcard.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [CMakeFiles/cmTC_1eb25.dir/HAVE_SOME_SOUNDCARD_H.c.o] Error 1
make: *** [cmTC_1eb25/fast] Error 2

Source:
/* */
#include <sys/soundcard.h>

int main(void){return 0;}

Determining if the function IceConnectionNumber exists in the ICE failed with the following output:
Change Dir: /Users/denisbopp/conky-for-macOS/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_8dde8/fast"
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_8dde8.dir/build.make CMakeFiles/cmTC_8dde8.dir/build
Building C object CMakeFiles/cmTC_8dde8.dir/CheckFunctionExists.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -std=c99  -DCHECK_FUNCTION_EXISTS=IceConnectionNumber   -o CMakeFiles/cmTC_8dde8.dir/CheckFunctionExists.c.o   -c /opt/local/share/cmake-3.11/Modules/CheckFunctionExists.c
Linking C executable cmTC_8dde8
/opt/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_8dde8.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -std=c99  -DCHECK_FUNCTION_EXISTS=IceConnectionNumber -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_8dde8.dir/CheckFunctionExists.c.o  -o cmTC_8dde8  -L/opt/local/lib -Wl,-rpath,/opt/local/lib -lICE 
ld: library not found for -lICE
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [cmTC_8dde8] Error 1
make: *** [cmTC_8dde8/fast] Error 2

**Comment by npyl** [comment]
Hi! Have you followed the [guide](https://github.com/Conky-for-macOS/conky-for-macOS/wiki/How-to-Build)

**Comment by DenisBopp** [comment]
Sorry, no! Do that now, but get this error!
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Xinerama_LIBRARIES (ADVANCED)
    linked by target "conky" in directory /Users/denisbopp/Downloads/Conky-for-macOS/src

-- Configuring incomplete, errors occurred!
See also "/Users/denisbopp/Downloads/Conky-for-macOS/build/CMakeFiles/CMakeOutput.log".
See also "/Users/denisbopp/Downloads/Conky-for-macOS/build/CMakeFiles/CMakeError.log".

**Comment by npyl** [comment]
It seems there is a problem with your [XQuartz](https://www.xquartz.org) installation.
Please try reinstalling XQuartz first and continue to guide.

Or, download [ManageConky](https://github.com/Conky-for-macOS/Manage-Conky/releases/tag/v0.7) which is the alternative of [conky-manager](https://github.com/teejee2008/conky-manager) and supports automatic installation and configuration of conky!

**Comment by DenisBopp** [comment]
Hi, I reinstall XQuartz, but now cmake don't find imlib2..
-- Checking for one of the modules 'imlib2;Imlib2'
CMake Error at /opt/local/share/cmake-3.11/Modules/FindPkgConfig.cmake:640 (message):
  None of the required 'imlib2;Imlib2' found
Call Stack (most recent call first):
  cmake/ConkyPlatformChecks.cmake:419 (pkg_search_module)
  CMakeLists.txt:36 (include)



imlib2 was installed and reinstalled!

**Comment by npyl** [comment]
I am not sure what the problem is since conky has been tested to build on macOS using [TravisCI](https://travis-ci.org/).  </br>
One wild guess though is that `brew link gettext --force` failed or hasn't been executed. </br>
If this issue gets more attention I will reopen it and investigate it further.
