### ISSUE TITLE
Sending the USR1 signal causes Xquartz to crash

### ISSUE THREAD

**Issue by matmunn** [Conky-for-macOS/conky-for-macOS#29]
When sending conky the USR1 signal, which is meant to have conky reload the config file, causes Xquartz to crash, which then causes conky to crash and exit.

**Comment by npyl** [comment]
Interesting, If I try with the command `killall -SIGUSR1 conky` it works.  Could this be a difference in usage between the linux and macOS killall?

**Comment by matmunn** [comment]
I just had another look at this and interestingly doing `kill -s SIGUSR1 pid` worked, then `kill -SIGUSR1 pid` worked and restarted conky, then Xquartz crashed ~5s after the second signal was sent to conky.

**Comment by npyl** [comment]
I can confirm this myself, lets see what the problem is.

**Comment by npyl** [comment]
Hi! Update on the problem: I think that disabling XDamage support makes the problem disappear.  Please recompile with `BUILD_XDAMAGE` set to `OFF`

**Comment by matmunn** [comment]
That seems to have fixed it for me. Thanks so much for working on this!

**Comment by npyl** [comment]
No problem!!! Glad it helped!
