### ISSUE TITLE
Conky can't open display

### ISSUE THREAD

**Issue by matmunn** [Conky-for-macOS/conky-for-macOS#38]
The last couple of times I've built conky and tried to run it it always fails to start with `conky: can't open display:`

On a 15" MBP with fresh install of macOS 10.13.6 it doesn't show any device that it failed to open:
![image](https://user-images.githubusercontent.com/65853/45017013-c3eddb00-b069-11e8-897a-a0d33544b233.png)

On a 13" MBP that I've previously run conky for macOS on it shows a path to Xquartz, I'll attach to this issue when I next use it.

**Comment by matmunn** [comment]
13" MBP that has previously run Conky for macOS fails to open Xquartz:
```
 $ conky
conky: can't open display: /private/tmp/com.apple.launchd.pWK9XHRw5z/org.macosforge.xquartz:0
```

**Comment by npyl** [comment]
This is really weird, on my macbook 13'' it works fine.  Could you please tell me the output of the command: 

`echo $DISPLAY`

**Comment by matmunn** [comment]
It's blank

**Comment by npyl** [comment]
Do you have any other software using XQuartz? Does this run fine? An example would be InkScape

**Comment by matmunn** [comment]
I just built and installed InkScape, it started fine. After quitting conky still didn't start and `$DISPLAY` is still blank

**Comment by matmunn** [comment]
Ok weird, after building InkScape I had to reboot for an unrelated problem and now conky is starting. I'll close this for now, and try again on the 13" MBP later on

**Comment by npyl** [comment]
the first time you install xquartz you need to reboot (re-login suffices i think) in order for the DISPLAY to be set correctly and other things.  Maybe that was the case?

**Comment by matmunn** [comment]
I've probably done something dumb like that, cheers for the help
