### ISSUE TITLE
The requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by ultratux** [Conky-for-macOS/conky-for-macOS#47]
Trying to install on a mac with 'brew install conky', but received 404 error.

Error message:
curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "conky"
Download failed: https://github.com/npyl/npyl.github.io/raw/master/Projects/conky/conky-1.11.1.tar.gz

**Comment by npyl** [comment]
Hi @ultratux,
Thank you for reporting this.

This particular issue has been fixed but I doubt the formula is ready.
You could run `brew update && brew install conky` again if you want to see if it fails only for me.

I am working on a fix for this, but some digging has to be done
and it may take time.
As a quick alternative, you could download [ManageConky](https://github.com/Conky-for-macOS/Manage-Conky/releases).

**Comment by npyl** [comment]
Hey @ultratux ,
Good news!
I think all problems have been fixed.
This means you can now install conky the way you wanted to begin with! :)

Give it a try and tell me.
Nick
